### PR TITLE
Add gcc, aarch64-linux-gnu-gcc, and arm-none-eabi-gcc

### PR DESCRIPTION
**Pull request by Kaz205**
Signed-off-by: Kazuki Hashimoto <kazukih@tuta.io>

### CODE REVIEW

**Comment by Panchajanya1999** [comment]
@Kaz205 CI is failing to compile due to limited storage.

**Comment by Kaz205** [comment]
Rip. Should I drop the patch or should we consider removing other packages?

**Comment by Kaz205** [comment]
Also It appears that GCC was already being installed via the base-devel package group.

**Comment by Kaz205** [comment]
> Rip. Should I drop the patch or should we consider removing other packages?

Or a different build server.

**Comment by Panchajanya1999** [comment]
> > Rip. Should I drop the patch or should we consider removing other packages?
> 
> Or a different build server.

can you try github actions?

**Pull request closed without merging**
